<?php

return [
    // Olahraga & Fitness
    'fa-futbol' => 'Futsal / Bola (fa-futbol)',
    'fa-person-running' => 'Pemain Berlari (fa-person-running)',
    'fa-person-walking' => 'Pemain Berjalan (fa-person-walking)',
    'fa-dumbbell' => 'Latihan Fisik / Gym (fa-dumbbell)',
    'fa-trophy' => 'Piala / Juara (fa-trophy)',
    'fa-medal' => 'Medali Penghargaan (fa-medal)',
    'fa-crown' => 'Mahkota / Juara 1 (fa-crown)',
    'fa-route' => 'Rute / Strategi (fa-route)',
    'fa-map' => 'Papan Taktik (fa-map)',
    'fa-stopwatch' => 'Stopwatch / Waktu (fa-stopwatch)',
    'fa-flag' => 'Bendera / Target (fa-flag)',
    'fa-heartbeat' => 'Detak Jantung (fa-heartbeat)',
    'fa-shoe-prints' => 'Jejak Sepatu (fa-shoe-prints)',
    
    // Grafik & Analisis
    'fa-chart-line' => 'Statistik Naik (fa-chart-line)',
    'fa-chart-bar' => 'Grafik Batang (fa-chart-bar)',
    'fa-chart-pie' => 'Diagram Lingkar (fa-chart-pie)',
    'fa-chart-column' => 'Grafik Kolom (fa-chart-column)',
    'fa-chart-area' => 'Grafik Area (fa-chart-area)',
    'fa-arrow-trend-up' => 'Tren Naik (fa-arrow-trend-up)',
    'fa-arrow-trend-down' => 'Tren Turun (fa-arrow-trend-down)',
    'fa-ranking-star' => 'Peringkat Bintang (fa-ranking-star)',
    'fa-percent' => 'Persentase / Diskon (fa-percent)',
    
    // Finansial & Kas
    'fa-money-bill-transfer' => 'Kas Keuangan (fa-money-bill-transfer)',
    'fa-wallet' => 'Dompet Digital (fa-wallet)',
    'fa-file-invoice-dollar' => 'Tagihan Kas (fa-file-invoice-dollar)',
    'fa-receipt' => 'Kuitansi / Kas (fa-receipt)',
    'fa-credit-card' => 'Kartu Kredit (fa-credit-card)',
    'fa-money-bill' => 'Uang Kertas (fa-money-bill)',
    'fa-money-bill-wave' => 'Uang Mengalir (fa-money-bill-wave)',
    'fa-coins' => 'Koin / Rupiah (fa-coins)',
    'fa-hand-holding-dollar' => 'Pemasukan Kas (fa-hand-holding-dollar)',
    'fa-piggy-bank' => 'Celengan / Tabungan (fa-piggy-bank)',
    'fa-dollar-sign' => 'Simbol Dollar (fa-dollar-sign)',
    'fa-rupiah-sign' => 'Simbol Rupiah (fa-rupiah-sign)',
    
    // Agenda, Waktu, & Kalender
    'fa-calendar-check' => 'Agenda & Absensi (fa-calendar-check)',
    'fa-calendar-days' => 'Kalender / Jadwal (fa-calendar-days)',
    'fa-calendar-plus' => 'Tambah Jadwal (fa-calendar-plus)',
    'fa-calendar-minus' => 'Hapus Jadwal (fa-calendar-minus)',
    'fa-clock' => 'Waktu / Jam (fa-clock)',
    'fa-hourglass-half' => 'Durasi / Waktu (fa-hourglass-half)',
    'fa-business-time' => 'Waktu Kerja (fa-business-time)',
    'fa-bell' => 'Notifikasi Lonceng (fa-bell)',
    'fa-bell-slash' => 'Senyap / Silent (fa-bell-slash)',
    
    // Pengguna & Manajemen
    'fa-users' => 'Kelompok Pemain (fa-users)',
    'fa-user-group' => 'Manajemen Klub (fa-user-group)',
    'fa-user-tie' => 'Manager / Coach (fa-user-tie)',
    'fa-user' => 'Profil Pengguna (fa-user)',
    'fa-address-card' => 'Kartu Nama Pemain (fa-address-card)',
    'fa-users-gear' => 'Pengaturan Anggota (fa-users-gear)',
    'fa-user-plus' => 'Tambah Anggota (fa-user-plus)',
    'fa-user-minus' => 'Hapus Anggota (fa-user-minus)',
    'fa-user-check' => 'Anggota Verifikasi (fa-user-check)',
    'fa-user-shield' => 'Admin Keamanan (fa-user-shield)',
    'fa-id-badge' => 'Kartu Identitas (fa-id-badge)',
    
    // Komunikasi & Kolaborasi
    'fa-bullhorn' => 'Pengumuman / Siaran (fa-bullhorn)',
    'fa-envelope' => 'Kotak Pesan / Email (fa-envelope)',
    'fa-envelope-open' => 'Pesan Terbuka (fa-envelope-open)',
    'fa-comments' => 'Obrolan Tim (fa-comments)',
    'fa-comment' => 'Komentar Tunggal (fa-comment)',
    'fa-phone' => 'Telepon / Kontak (fa-phone)',
    'fa-handshake' => 'Sponsorship (fa-handshake)',
    'fa-share-nodes' => 'Bagikan Konten (fa-share-nodes)',
    'fa-thumbs-up' => 'Suka / Like (fa-thumbs-up)',
    
    // Sistem & Arsitektur
    'fa-cubes' => 'Multi-Tenant (fa-cubes)',
    'fa-cube' => 'Kubus / Tenant (fa-cube)',
    'fa-gauge-high' => 'Dasbor Ringkasan (fa-gauge-high)',
    'fa-lock' => 'Sistem Terkunci (fa-lock)',
    'fa-unlock' => 'Sistem Terbuka (fa-unlock)',
    'fa-shield-halved' => 'Keamanan Platform (fa-shield-halved)',
    'fa-key' => 'Kunci Akses (fa-key)',
    'fa-gear' => 'Pengaturan / Setelan (fa-gear)',
    'fa-gears' => 'Beberapa Setelan (fa-gears)',
    'fa-server' => 'Server Hosting (fa-server)',
    'fa-database' => 'Penyimpanan Data (fa-database)',
    'fa-circle-nodes' => 'Integrasi Sistem (fa-circle-nodes)',
    'fa-cloud' => 'Penyimpanan Awan (fa-cloud)',
    'fa-cloud-arrow-up' => 'Unggah ke Awan (fa-cloud-arrow-up)',
    'fa-cloud-arrow-down' => 'Unduh dari Awan (fa-cloud-arrow-down)',
    'fa-wifi' => 'Koneksi Internet (fa-wifi)',
    'fa-terminal' => 'Konsol Perintah (fa-terminal)',
    'fa-bug' => 'Laporan Kutu (fa-bug)',
    
    // Antarmuka & Navigasi
    'fa-gem' => 'Member Premium (fa-gem)',
    'fa-star' => 'Pemain Bintang (fa-star)',
    'fa-heart' => 'Kesehatan / Favorit (fa-heart)',
    'fa-circle-info' => 'Informasi / Detail (fa-circle-info)',
    'fa-circle-question' => 'Pertanyaan / Help (fa-circle-question)',
    'fa-circle-exclamation' => 'Peringatan / Alert (fa-circle-exclamation)',
    'fa-circle-check' => 'Selesai / Sukses (fa-circle-check)',
    'fa-circle-xmark' => 'Batal / Salah (fa-circle-xmark)',
    'fa-pen-to-square' => 'Tulis / Edit (fa-pen-to-square)',
    'fa-trash-can' => 'Tong Sampah (fa-trash-can)',
    'fa-magnifying-glass' => 'Pencarian (fa-magnifying-glass)',
    'fa-file-pdf' => 'Ekspor PDF (fa-file-pdf)',
    'fa-file-excel' => 'Ekspor Excel (fa-file-excel)',
    'fa-file-word' => 'Ekspor Word (fa-file-word)',
    'fa-file-lines' => 'Berkas Dokumen (fa-file-lines)',
    'fa-folder' => 'Folder Berkas (fa-folder)',
    'fa-folder-open' => 'Folder Terbuka (fa-folder-open)',
    'fa-location-dot' => 'Lokasi Lapangan (fa-location-dot)',
    'fa-location-crosshairs' => 'Target Lokasi (fa-location-crosshairs)',
    'fa-earth-asia' => 'Bahasa / Publik (fa-earth-asia)',
    'fa-laptop' => 'Sistem Komputer (fa-laptop)',
    'fa-mobile-screen-button' => 'Aplikasi HP (fa-mobile-screen-button)',
    'fa-print' => 'Cetak Laporan (fa-print)',
    'fa-link' => 'Tautan / Link (fa-link)',
    'fa-code' => 'Pengembang / Kode (fa-code)',
    'fa-qrcode' => 'QR Code QRIS (fa-qrcode)',
    'fa-tag' => 'Label Harga (fa-tag)',
    'fa-tags' => 'Paket Berlangganan (fa-tags)',
    'fa-ticket' => 'Tiket / Sparring (fa-ticket)',
    'fa-house' => 'Halaman Rumah / Home (fa-house)',
    'fa-building' => 'Gedung GOR (fa-building)',
];
